repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          "--remove-all-unused-imports",
          "--remove-unused-variables",
          "--in-place",
          "--recursive"
        ]

  # import整理: isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        files: ^codinsight/

  # コード整形: Black
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        files: ^codinsight/

  # Lint: flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        files: ^codinsight/
        additional_dependencies: [flake8-bugbear]
        args: ["--max-line-length=88"]

  # 型チェック: mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        language_version: python3
        files: ^codinsight/
        additional_dependencies:
        - pydantic>=2.0

  # docstring チェック: pydocstyle
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [
          "--convention=numpy",
          "--add-ignore=D100,D104,D400,D415"
        ]
        language_version: python3
        files: ^codinsight/src/

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        args: ["-s", "numpy"]

  # セキュリティチェック: bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3
        files: ^codinsight/src/
