repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^codinsight/
      - id: ruff-format
        files: ^codinsight/

  # 型チェック: mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        language_version: python3
        files: ^codinsight/
        additional_dependencies:
        - pydantic>=2.0

  # docstring チェック: pydocstyle
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [
          "--convention=numpy",
          "--add-ignore=D100,D104,D400,D415"
        ]
        language_version: python3
        files: ^codinsight/src/

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        args: ["-s", "numpy"]

  # セキュリティチェック: bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language_version: python3
        files: ^codinsight/src/
